Style/For:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false
  
Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false